# Generated by Django 3.2.6 on 2021-10-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lib_bookmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lib_bookmodel',
            name='is_issued',
        ),
        migrations.RemoveField(
            model_name='lib_bookmodel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lib_bookmodel',
            name='user_id',
        ),
    ]
